#!/usr/bin/env bash
# sync_from_wyeast.sh — re-copy the Family Archive import closure from a Wyeast
# checkout and re-apply this repo's local modifications.
#
#   ./sync_from_wyeast.sh /path/to/Wyeast
#
# Afterwards: review `git diff`, run ./run_tests.sh, and update the commit sha
# in UPSTREAM.md.

set -euo pipefail
_HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="${1:-}"
if [[ -z "$SRC" || ! -d "$SRC/wyeast/core" ]]; then
  echo "usage: $0 /path/to/Wyeast   (a checkout with wyeast/core/ in it)" >&2
  exit 1
fi
SRC="$(cd "$SRC" && pwd)"
cd "$_HERE"

TOOLS=(family_archive.py _archive_data.py build_fts.py export_delivery.py gen_email_threads.py)
CORE=(__init__.py audience.py config.py custody.py delivery.py errors.py filetypes.py
      io.py media.py moves.py paths.py release.py safe_names.py)
TESTS=(test_family_archive test_archive_data test_build_fts test_export_delivery
       test_core_delivery test_audience test_filetypes test_errors test_io test_moves
       test_paths_custody test_release test_release_enforcement test_release_verbs
       test_safe_names test_gen_email_threads_audience)

echo "==> copying from $SRC"
for f in "${TOOLS[@]}";  do cp "$SRC/tools/$f" tools/; done
cp "$SRC/wyeast/__init__.py" wyeast/
for f in "${CORE[@]}";   do cp "$SRC/wyeast/core/$f" wyeast/core/; done
for t in "${TESTS[@]}";  do cp "$SRC/tests/unit/$t.py" tests/unit/; done
cp "$SRC/tests/conftest.py" tests/
rm -rf report_assets && cp -r "$SRC/report_assets" .
cp "$SRC/config/pipeline_config.json" "$SRC/config/file_types.json" \
   "$SRC/config/file_types.schema.json" config/
find . -name __pycache__ -type d -exec rm -rf {} + 2>/dev/null || true

echo "==> re-applying local modifications (see UPSTREAM.md)"
python3 - "$SRC" <<'PYEOF'
import sys
from pathlib import Path
src = Path(sys.argv[1])

# 1. Zone-B-literal shebangs.
for name in ("tools/family_archive.py", "tools/export_delivery.py"):
    p = Path(name)
    lines = p.read_text().splitlines(keepends=True)
    if lines[0].startswith("#!/opt/estate-pipeline"):
        lines[0] = "#!/usr/bin/env python3\n"
        p.write_text("".join(lines))
        print("    shebang: %s" % name)

# 2. make_case fixture, lifted out of the (uncarried) explorer test module.
tbe = (src / "tests/unit/test_build_explorer.py").read_text().splitlines(keepends=True)
start = next(i for i, l in enumerate(tbe) if l.startswith("def _write("))
end = next(i for i, l in enumerate(tbe) if l.startswith("def _sign_case("))
Path("tests/unit/_case_fixture.py").write_text('''"""Shared test fixture: build a minimal but realistic finished case on disk.

Lifted verbatim from Wyeast's tests/unit/test_build_explorer.py (which cannot
come along, since tools/build_explorer.py is outside the Family Archive import
closure). Upstream, tests/unit/test_family_archive.py loads `make_case` out of
that module by path; here it imports it from this file instead. Regenerated by
sync_from_wyeast.sh.
"""
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

SECRET = "SECRETVALUE_DO_NOT_LEAK"
OCR_TOKEN = "ocrtokenxyz"


''' + "".join(tbe[start:end]).rstrip() + "\n")
print("    regenerated tests/unit/_case_fixture.py")

p = Path("tests/unit/test_family_archive.py")
s = p.read_text()
old = '''# Load make_case from the explorer test module by path.
_spec = importlib.util.spec_from_file_location(
    "tbe", str(REPO / "tests" / "unit" / "test_build_explorer.py"))
_tbe = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_tbe)
make_case = _tbe.make_case'''
new = '''# Upstream loads make_case out of tests/unit/test_build_explorer.py by path;
# that module tests tools/build_explorer.py, which is outside this repo's import
# closure, so the fixture lives in _case_fixture.py here instead.
sys.path.insert(0, str(Path(__file__).resolve().parent))
import _case_fixture as _tbe  # noqa: E402
make_case = _tbe.make_case'''
if old not in s:
    sys.exit("    ERROR: the make_case loader block in test_family_archive.py no "
             "longer matches. Re-patch it by hand and update this script.")
s = s.replace(old, new)
s = s.replace("Reuses make_case from test_build_explorer and",
              "Reuses make_case from _case_fixture and")
s = s.replace("# make_case (test_build_explorer) already seeds",
              "# make_case (_case_fixture) already seeds")
p.write_text(s)
print("    patched tests/unit/test_family_archive.py")

# 3. Drop the llm_synthesis delegation test (that stage is not carried).
p = Path("tests/unit/test_safe_names.py")
lines = p.read_text().splitlines(keepends=True)
start = next((i for i, l in enumerate(lines)
              if l.startswith("def test_safe_album_dirname_delegates(")), None)
if start is None:
    sys.exit("    ERROR: test_safe_album_dirname_delegates not found in "
             "test_safe_names.py — check whether the drop is still needed.")
p.write_text("".join(lines[:start]) +
    "# NOTE: upstream also has test_safe_album_dirname_delegates, which asserts the\n"
    "# same delegation from wyeast.stages.llm_synthesis. That stage is outside the\n"
    "# Family Archive import closure and is not carried here, so the test is dropped.\n")
print("    dropped test_safe_album_dirname_delegates")
PYEOF

if [[ -f "$SRC/tests/unit/test_config.py" ]]; then
  rm -f tests/unit/test_config.py   # imports wyeast.core.registry; not carried
fi

echo
echo "==> upstream commit"
(cd "$SRC" && git rev-parse HEAD 2>/dev/null || echo "(not a git checkout)")
echo
echo "Next: git diff, ./run_tests.sh, then update the sha in UPSTREAM.md."
