"""Shared test fixture: build a minimal but realistic finished case on disk.

Lifted verbatim from Wyeast's tests/unit/test_build_explorer.py (which cannot
come along, since tools/build_explorer.py is outside the Family Archive import
closure). Upstream, tests/unit/test_family_archive.py loads `make_case` out of
that module by path; here it imports it from this file instead. Regenerated by
sync_from_wyeast.sh.
"""
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

SECRET = "SECRETVALUE_DO_NOT_LEAK"
OCR_TOKEN = "ocrtokenxyz"


def _write(path, obj):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj), encoding="utf-8")


def make_case(tmp_path, *, delivery_blocked=False, complete=True):
    """Build a minimal but realistic finished case under tmp_path/cases/CASE_T."""
    cases = tmp_path / "cases"
    case = cases / "CASE_T"
    md = case / "output" / "metadata"
    archive = case / "output" / "archive"
    md.mkdir(parents=True)
    archive.mkdir(parents=True)

    # Two real delivered photos on disk (so the family universe keeps them).
    src_a = "/work/extracted/a.jpg"
    src_b = "/work/extracted/b.jpg"
    arc_a = archive / "a.jpg"
    arc_b = archive / "b.jpg"
    arc_a.write_bytes(b"\xff\xd8\xff\xd9")
    arc_b.write_bytes(b"\xff\xd8\xff\xd9")

    doc_fin = "/work/docs/invoice.pdf"
    doc_cred = "/work/docs/passwords.txt"

    _write(md / "_run_state.json", {
        "schema_version": 1, "case_id": "CASE_T", "stage": "reconciliation",
        "name": "reconciliation", "status": "complete" if complete else "started",
    })
    _write(md / "case_summary.json", {
        "schema_version": 1, "case_id": "CASE_T", "generated_at": "2026-06-28T00:00:00",
        "total_photos": 2, "video_delivered": 0, "total_videos": 0, "total_documents": 2,
        "photo_clusters": [{"person_id": "Person_01", "photo_count": 1,
                            "summary": "A person.", "significance": 3}],
        "scene_counts": {"everyday life": 2},
        "document_counts": {"financial": 1, "account_credentials": 1},
        "document_classifications": [
            {"file": doc_fin, "filename": "invoice.pdf", "category": "financial",
             "significance": 4, "summary": "An invoice."},
            {"file": doc_cred, "filename": "passwords.txt", "category": "account_credentials",
             "significance": 5, "summary": "Login is " + SECRET},
        ],
        "audio_classifications": [], "audio_counts": {},
        "ranked_items": [{"type": "photo_cluster", "label": "Person_01",
                          "person_id": "Person_01", "score": 7.3, "signals": {}}],
        "credentials_report": {"critical_count": 1, "informational_count": 0,
                               "items": [{"file": "passwords.txt", "source": "ocr",
                                          "credential_types": ["password"], "severity": "critical",
                                          "secret_value": SECRET}]},
        "limitations": [], "stages_completed": ["reconciliation"],
        "export_gate": {"operator_waiver_required": delivery_blocked,
                        "waiver_reason": "delivery quarantine incomplete" if delivery_blocked else "",
                        "delivery_blocked": delivery_blocked, "branded_incomplete": delivery_blocked,
                        "reasons": ["Delivery quarantine incomplete"] if delivery_blocked else []},
    })
    _write(md / "scene_index.json", {
        "clip_results": {
            src_a: {"category": "everyday life", "confidence": 0.9, "delivered": True},
            src_b: {"category": "everyday life", "confidence": 0.8, "delivered": True},
        },
        "junk_results": {},
    })
    _write(md / "archive_map.json", {
        "schema_version": 1, "case_id": "CASE_T", "archive_root": str(archive),
        "entries": {src_a: str(arc_a), src_b: str(arc_b)},
    })
    _write(md / "metadata_index.json", {
        src_a: {"timestamp": "2020-05-01T10:00:00", "place": "Portland_Oregon",
                "gps": {"lat": 45.5, "lon": -122.6}},
        src_b: {"timestamp": "2019-01-01T09:00:00", "place": None, "gps": None},
    })
    _write(md / "geo_cluster_index.json", {
        src_a: {"gps_trip_name": "Portland_Oregon", "compound_label": "Portland"},
    })
    _write(md / "face_clustering.json", {
        "person_clusters": {"Person_01": [src_a]}, "cluster_identities": {},
        "enrollment": {"enabled": False}, "noise_files": [],
    })
    # OCR sidecar text carries a distinctive token that must reach the search index.
    _write(md / "ocr_index.json", [
        {"file": doc_fin, "ocr_text": "invoice total due " + OCR_TOKEN,
         "method": "tesseract", "sidecar": "x.txt", "text_kind": "printed"},
    ])
    _write(md / "transcription_index.json", [])

    # Examiner-only review surfaces — these must NEVER reach a family bundle.
    _write(md / "quarantine_manifest.json", {
        "entries": [{"file": "/work/quarantine/bad.jpg", "filter": "explicit_sexual_imagery",
                     "canonical_path": "/cases/CASE_T/quarantine/bad.jpg",
                     "quarantine_path": "/cases/CASE_T/quarantine/bad.jpg",
                     "timestamp": "2026-06-28T00:00:00"}],
        "released": [],
    })
    _write(md / "sensitive_scan_index.json", {
        "/work/sensitive/x.jpg": {"human_review_required": True,
                                  "sensitivity_filters": {"explicit_sexual_imagery": 1}},
    })
    _write(md / "human_review_required.json", {"generated_at": "x", "paths": ["/work/sensitive/x.jpg"]})
    _write(md / "reconciliation_manifest.json", {
        "needs_examiner_review": True, "attention_counts": {"unknown_type": 1},
        "delivery": {}, "original_files_remaining": {}, "review_items": ["Check unknown types"],
    })
    return cases, case
